name: ces

services:
  postgres:
    image: postgres:16-alpine
    container_name: ces-postgres
    environment:
      POSTGRES_DB: ces_erp
      POSTGRES_USER: ces_user
      POSTGRES_PASSWORD: ces_password
    ports:
      - "5434:5432"
    volumes:
      - ces_postgres_data:/var/lib/postgresql/data
    networks:
      - ces-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ces-redis
    ports:
      - "6381:6379"
    volumes:
      - ces_redis_data:/data
    networks:
      - ces-network
    restart: unless-stopped

volumes:
  ces_postgres_data:
  ces_redis_data:

networks:
  ces-network:
    driver: bridge