package com.ces.erp.common.seeder;

import com.ces.erp.customer.entity.Customer;
import com.ces.erp.customer.repository.CustomerRepository;
import com.ces.erp.enums.CustomerStatus;
import com.ces.erp.enums.RiskLevel;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Set;

/**
 * Mənbə: "Müştəri Bazası.xlsx" → "Müştəri bazası" vərəqi (real şirkət siyahısı).
 */
@Component
@Order(4)
@RequiredArgsConstructor
@Slf4j
public class CustomerSeeder implements CommandLineRunner {

    private final CustomerRepository customerRepository;

    @Override
    @Transactional
    public void run(String... args) {
        if (customerRepository.count() > 0) return;
        log.info("Müştərilər seed edilir...");

        List<Customer> customers = List.of(

                Customer.builder()
                        .companyName("A+A ŞİRKƏTLƏR QRUPU MMC")
                        .voen("1400109001")
                        .address("Nərimanov rayonu, Əhmədbəy Ağaoğlu,24b Canaqqala restoranının yanı")
                        .supplierPerson("Andrey bəy")
                        .supplierPhone("+994503973020")
                        .officeContactPerson("Tarana xanım")
                        .officeContactPhone("+994503534946")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.ACTIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("PREDSOL MMC")
                        .voen("1503348711")
                        .address("Badamdar, Mikayıl Müşfiq 1 C Bakı")
                        .supplierPerson("Məcid bəy")
                        .supplierPhone("+994552130443")
                        .officeContactPerson("İlhama xanım")
                        .officeContactPhone("+994552201472")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.ACTIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("SİNERJİ PRO QSC")
                        .voen("1501502151")
                        .address("Bakı Şəhəri Nərimanov Rayonu Yaşar Hüseynov 17-(Gürcüstan Səfirliyi ilə üzbəüz VİLLA PLAZA)")
                        .supplierPerson("İsmayıl bəy")
                        .supplierPhone("+994556673067")
                        .officeContactPerson("Murad bəy")
                        .officeContactPhone("+994102532838")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.ACTIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("GİLTEX MMC")
                        .voen("2903375461")
                        .address("Sumqayıt şəh. Sülh küç.")
                        .supplierPerson("İnayət bəy")
                        .supplierPhone("+994502905093")
                        .officeContactPerson("Günay xanım (sənədləşmə)")
                        .officeContactPhone("+994502907971")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.ACTIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("ZİRVE YATIRIM")
                        .voen("1504542991")
                        .supplierPerson("Amil bəy")
                        .supplierPhone("+994502121253")
                        .officeContactPerson("Lamiyə xanım")
                        .officeContactPhone("+994555694091")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.ACTIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("İTİCKET PRODUCTİON")
                        .voen("1702333811")
                        .address("Af mall ticarət mərəzi 14-cü mərtəbə")
                        .supplierPerson("Afgan bəy")
                        .supplierPhone("+994709004540")
                        .officeContactPerson("Aygün xanım")
                        .officeContactPhone("+994504768989")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("EVRASCONE ASC")
                        .voen("1000085511")
                        .supplierPerson("Nicat bəy")
                        .supplierPhone("+994502707756")
                        .officeContactPerson("Nicat bəy")
                        .officeContactPhone("+994502707756")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.ACTIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("ATS MİLL MMC")
                        .voen("3100856341")
                        .address("Abşoren rayonu Şamaxı şossesi 129")
                        .supplierPerson("Ceyhun bəy")
                        .supplierPhone("+994102533030")
                        .officeContactPerson("Elməddin bəy(sənədləşmə)")
                        .officeContactPhone("+994512054585")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.ACTIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("SİLO CONSTRUCTİON MMC")
                        .voen("1005856871")
                        .supplierPerson("Məhsul şəxs")
                        .supplierPhone("+994506250203")
                        .officeContactPerson("Məhsul şəxs")
                        .officeContactPhone("+994506250203")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.VARIABLE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("İRMİŞ İNŞAAT")
                        .voen("1506820931")
                        .supplierPerson("Şenöl bəy")
                        .supplierPhone("+994998611299")
                        .officeContactPerson("Şenöl bəy")
                        .officeContactPhone("+994998611299")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.ACTIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("VÖRKPLEYS İNTERİORS MMC")
                        .voen("1700942011")
                        .address("Marine plaza")
                        .supplierPerson("Azər bəy")
                        .supplierPhone("+994512059086")
                        .officeContactPerson("Aytac xanım")
                        .officeContactPhone("+994512448736")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("İMPROTEX TRUCKS AND BUSES MMC")
                        .voen("1400726411")
                        .address("Salyan şossesi")
                        .supplierPerson("Murad bəy")
                        .supplierPhone("+994502223025")
                        .officeContactPerson("Murad bəy")
                        .officeContactPhone("+994502223025")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.HIGH)
                        .notes("Ödəniş sıxıntısı")
                        .build(),

                Customer.builder()
                        .companyName("BAKU MEDİA MƏRKƏSİ MMC")
                        .voen("1402552521")
                        .address("Mikayl Müşfiq küç,2H Badamdar")
                        .supplierPerson("Cəmilə xanım")
                        .supplierPhone("+994507035063")
                        .officeContactPerson("Cəmilə xanım")
                        .officeContactPhone("+994507035063")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("MET-AK MMC")
                        .voen("1500018681")
                        .address("Nərimanov rayonu Böyükşor küç Daş karxana 2-ci dalan 15A")
                        .supplierPerson("Fərid bəy")
                        .supplierPhone("+994102282868")
                        .officeContactPerson("Fərid bəy")
                        .officeContactPhone("+994102282868")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("FORTİS İNDUSTRİAL SOLUTİONS MMC")
                        .voen("1502433941")
                        .address("Azure Biznes Mərkəzi 11 ci mərtəbə 69 otaq")
                        .supplierPerson("Kamal bəy")
                        .supplierPhone("+994502613558")
                        .officeContactPerson("Humay xanım")
                        .officeContactPhone("+994502613557")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("İKMA SERVİCE MMC")
                        .voen("1400652401")
                        .address("Ağa Biznez Mərkəzi")
                        .supplierPerson("Elçin bəy")
                        .supplierPhone("+994502514882")
                        .officeContactPerson("Fəhruz bəy(mühasib)")
                        .officeContactPhone("+994502290613")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.VARIABLE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("ULU AGRO MMC")
                        .voen("4300489071")
                        .address("QAX")
                        .supplierPerson("Cəlal bəy")
                        .supplierPhone("+994502113420")
                        .officeContactPerson("Azər bəy(mühasib)")
                        .officeContactPhone("+994512443313")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.ACTIVE)
                        .riskLevel(RiskLevel.MEDIUM)
                        .notes("Ödəniş sıxıntısı")
                        .build(),

                Customer.builder()
                        .companyName("FAM CONSTRUCTION MMC")
                        .voen("1703225901")
                        .address("Əhməd Rəcəbli Bakı 1075")
                        .supplierPerson("Toğrul bəy")
                        .supplierPhone("+994776366676")
                        .officeContactPerson("Nailə xanım (mühasib)")
                        .officeContactPhone("+994512252770")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.VARIABLE)
                        .riskLevel(RiskLevel.LOW)
                        .notes("Orta dərəcəli ödəniş sıxıntısı")
                        .build(),

                Customer.builder()
                        .companyName("DRİLL AND CUT QSC")
                        .voen("1405175861")
                        .address("Salyan şossesi")
                        .supplierPerson("Həmzə bəy")
                        .supplierPhone("+994502428847")
                        .officeContactPerson("Flora xanım (mühasibatlıq)")
                        .officeContactPhone("+994503505886")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.MEDIUM)
                        .notes("Orta dərəcəli ödəniş sıxıntısı")
                        .build(),

                Customer.builder()
                        .companyName("ROAD AND CONSTRUCTİON MMC")
                        .voen("1306237991")
                        .address("Luxen plaza 7-ci mərtəbə")
                        .supplierPerson("Səxavət bəy (Təchizat müdürü)")
                        .supplierPhone("+994552201915")
                        .officeContactPerson("Ramal bəy")
                        .officeContactPhone("+994515013733")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.MEDIUM)
                        .notes("Lahiyədən çıxış")
                        .build(),

                Customer.builder()
                        .companyName("AZBADAM MMC")
                        .voen("2004095531")
                        .address("Türkan")
                        .supplierPerson("İlkin bəy (Satınalma üzrə mütəxəsis)")
                        .supplierPhone("+994512017696")
                        .officeContactPerson("Rövşən bəy (Satınalma üzrə menecer)")
                        .officeContactPhone("+994512017670")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.ACTIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("AZEL TEXNİKA MMC")
                        .voen("3103939331")
                        .supplierPerson("Azər bəy (Təsisçi direktor)")
                        .supplierPhone("+994557011636")
                        .officeContactPerson("Gülşən xanım (maliyyə)")
                        .officeContactPhone("+994503566347")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.MEDIUM)
                        .notes("Orta dərəcəli ödəniş sıxıntısı")
                        .build(),

                Customer.builder()
                        .companyName("İSTANBUL TEXNİK")
                        .voen("1405739361")
                        .officeContactPerson("Hüseyn bəy (maliyyə)")
                        .officeContactPhone("+994555800367")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("NATRON İNŞAAT")
                        .voen("1406800611")
                        .supplierPerson("Nurullah bəy")
                        .supplierPhone("+994517190452")
                        .officeContactPerson("İlahə xanım(Sənədləşmə)")
                        .officeContactPhone("+994509817701")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("STARMİNİNG")
                        .voen("1003366361")
                        .address("Bayıl Plaza")
                        .supplierPerson("Ozal bəy")
                        .supplierPhone("+994554099008")
                        .officeContactPerson("Ayxan bəy (Sənədləşmə)")
                        .officeContactPhone("+994554090939")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("BAKU EXPO CENTER")
                        .supplierPerson("Elnur bəy")
                        .supplierPhone("+994503215933")
                        .officeContactPerson("Elnur bəy")
                        .officeContactPhone("+994503215933")
                        .paymentTypes(Set.of("CASH"))
                        .status(CustomerStatus.VARIABLE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("MELİSA PARK")
                        .supplierPerson("Kamandar bəy")
                        .supplierPhone("+994502549887")
                        .officeContactPerson("Aysel xanım (Sənədləşmə)")
                        .officeContactPhone("+994102654472")
                        .paymentTypes(Set.of("CASH"))
                        .status(CustomerStatus.VARIABLE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("AZCD")
                        .voen("1404868241")
                        .address("Bakı şəhəri Nərimanov r-nu Həsən Əliyev küç 79, AZ1110")
                        .supplierPerson("Elşən Məcidov")
                        .supplierPhone("+994552085695")
                        .officeContactPerson("Şahnaz xanım (sənədləşmə)")
                        .officeContactPhone("+994554440933")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.VARIABLE)
                        .riskLevel(RiskLevel.MEDIUM)
                        .notes("Orta dərəcəli ödəniş sıxıntısı")
                        .build(),

                Customer.builder()
                        .companyName("ERS")
                        .voen("2902062861")
                        .address("Salyan şossesi")
                        .supplierPerson("Hacı bəy")
                        .supplierPhone("+994502558189")
                        .officeContactPerson("Anar bəy (mühasib)")
                        .officeContactPhone("+994502785333")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.VARIABLE)
                        .riskLevel(RiskLevel.MEDIUM)
                        .notes("Orta dərəcəli ödəniş sıxıntısı")
                        .build(),

                Customer.builder()
                        .companyName("UPS")
                        .voen("3001828671")
                        .supplierPerson("Vüsal bəy")
                        .officeContactPerson("İnqilab bəy (sənədləşmə,ödəniş)")
                        .officeContactPhone("+994513500171")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.ACTIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("PERLA MEBEL")
                        .supplierPerson("Allahverdi bəy")
                        .supplierPhone("+994552077747")
                        .paymentTypes(Set.of("CASH"))
                        .status(CustomerStatus.VARIABLE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("KRİSTAL BAKI")
                        .voen("3103396091")
                        .supplierPerson("Nicat bəy")
                        .supplierPhone("+994512018182")
                        .officeContactPerson("Səid bəy")
                        .officeContactPhone("+994102560561")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("GRAND AGRO")
                        .voen("1403644931")
                        .address("Çınar Plaza")
                        .supplierPerson("Ceyhunə xanım")
                        .supplierPhone("+994502788099")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.ACTIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("MİNERA")
                        .voen("1501982641")
                        .address("Nerimanov ray Asiq Molla Cume kucesi 56/2A.Omur klinikasinin yani Minera 5 mer bina")
                        .supplierPerson("Rüstəm bəy")
                        .supplierPhone("+994502077747")
                        .officeContactPerson("Firuzə xanım (Sənədləşmə)")
                        .officeContactPhone("+994705963107")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.VARIABLE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("DİBS")
                        .voen("290192861")
                        .address("Ağ şəhər biznes mərkəzi 8 noyabr prs 5 ci mərtəbə KİNGSPAN")
                        .supplierPerson("İlkin bəy (direktor)")
                        .supplierPhone("+994502501545")
                        .officeContactPerson("Elçin bəy")
                        .officeContactPhone("+994502306685")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.VARIABLE)
                        .riskLevel(RiskLevel.MEDIUM)
                        .notes("Orta dərəcəli ödəniş sıxıntısı")
                        .build(),

                Customer.builder()
                        .companyName("Azorel")
                        .voen("1700196501")
                        .supplierPerson("Elşən bəy")
                        .supplierPhone("+994558516666")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.VARIABLE)
                        .riskLevel(RiskLevel.MEDIUM)
                        .notes("Orta dərəcəli ödəniş sıxıntısı")
                        .build(),

                Customer.builder()
                        .companyName("ND COMPANY")
                        .voen("10065191981")
                        .address("İbrahim Paşa Dadaşov ev 27 BMS ilə üzbəüz")
                        .supplierPerson("Səbuhi bəy")
                        .supplierPhone("+994555110022")
                        .officeContactPerson("Maliyyə")
                        .officeContactPhone("+994555116122")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.HIGH)
                        .notes("Ödəniş sıxıntısı")
                        .build(),

                Customer.builder()
                        .companyName("ATS SOY")
                        .voen("1503242161")
                        .supplierPerson("Eldar bəy")
                        .supplierPhone("+994102656624")
                        .officeContactPerson("Eldar bəy")
                        .officeContactPhone("+994102656624")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.VARIABLE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("Qəbələ Konserv Zavodu")
                        .voen("4400247661")
                        .address("Xocasən Pepsi zavod")
                        .supplierPerson("Elçin bəy")
                        .supplierPhone("+994502909948")
                        .officeContactPerson("Elçin bəy")
                        .officeContactPhone("+994502909948")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("NETTES")
                        .voen("1408800201")
                        .supplierPerson("Mustafa İçli")
                        .supplierPhone("+994518937813")
                        .officeContactPerson("Mustafa İçli")
                        .officeContactPhone("+994518937813")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("AZƏRİSTEEL")
                        .voen("2004894661")
                        .address("Sahil Qəsəbəsi")
                        .supplierPerson("Elnarə xanım")
                        .supplierPhone("+994502682816")
                        .officeContactPerson("Elnarə xanım")
                        .officeContactPhone("+994502682816")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.MEDIUM)
                        .notes("Orta dərəcəli ödəniş sıxıntısı")
                        .build(),

                Customer.builder()
                        .companyName("ACE FORVARDİNG")
                        .voen("1702619381")
                        .address("Salyan şossesi")
                        .supplierPerson("Fəxri Süleymanov")
                        .supplierPhone("+994502623434")
                        .officeContactPerson("Fəxri Süleymanov")
                        .officeContactPhone("+994502623434")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.VARIABLE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("AMET SERVİCES")
                        .voen("1302992001")
                        .address("Salyan şossesi")
                        .officeContactPerson("Səmra xanım")
                        .officeContactPhone("+994552030610")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("ANG")
                        .voen("1402057841")
                        .address("Ağ şəhər")
                        .supplierPerson("Sənan bəy")
                        .supplierPhone("+994502508341")
                        .officeContactPerson("Əli bəy (sənədləşmə)")
                        .officeContactPhone("+994777278180")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("FLEXI-TECH")
                        .voen("1307521421")
                        .supplierPerson("Elnur bəy")
                        .supplierPhone("+994702142488")
                        .officeContactPerson("Elnur bəy")
                        .officeContactPhone("+994702142488")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("CONRAD MMC")
                        .voen("6200068521")
                        .address("Nərimanov rayonu 2036-cı məhəllə Köndələn 10 küçəsi 1B mərtəbə 1 qapı 3")
                        .supplierPerson("İlyas bəy")
                        .supplierPhone("+994502078894")
                        .officeContactPerson("İlyas bəy")
                        .officeContactPhone("+994502078894")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.HIGH)
                        .notes("Ödəniş sıxıntısı")
                        .build(),

                Customer.builder()
                        .companyName("ELEL Construction")
                        .voen("1306662101")
                        .supplierPerson("Elçin bəy")
                        .supplierPhone("+994505899799")
                        .officeContactPerson("Elçin bəy")
                        .officeContactPhone("+994505899799")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.MEDIUM)
                        .build(),

                Customer.builder()
                        .companyName("UNI KO")
                        .voen("1001142901")
                        .address("İzzət orucov küç AZ1025 Qənimətlər Parkının yanı")
                        .supplierPerson("Yarmet bəy")
                        .supplierPhone("+994512073891")
                        .officeContactPerson("Yarmet bəy")
                        .officeContactPhone("+994512073891")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("ROYAL DEVELOPMENT")
                        .voen("1702672191")
                        .address("11 ci post RD sahə ofisi Ahmet bəy Yasamal royal Park")
                        .supplierPerson("Ahmet bəy")
                        .supplierPhone("+994512058261")
                        .officeContactPerson("Ahmet bəy")
                        .officeContactPhone("+994512058261")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("YKT TİKİNTİ MMC")
                        .voen("1301523921")
                        .address("Af mall, səməd vurğun küçə girişindən sol liftlı 15 ci mər ən sol qapı(AGE MMC)")
                        .officeContactPerson("Elvira xanım")
                        .officeContactPhone("+994519206382")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.HIGH)
                        .notes("Ödəniş sıxıntısı")
                        .build(),

                Customer.builder()
                        .companyName("DƏMİR YUMRUQ")
                        .voen("1605191131")
                        .address("See Breeze 31 ci dalan")
                        .supplierPerson("Turqut")
                        .supplierPhone("+994502113213")
                        .officeContactPerson("Tural bəy")
                        .officeContactPhone("+994502344190")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.HIGH)
                        .notes("Ödəniş sıxıntısı")
                        .build(),

                Customer.builder()
                        .companyName("AAC")
                        .voen("1401386761")
                        .address("Salyan şossesi")
                        .supplierPerson("Tural bəy")
                        .supplierPhone("+994552058605")
                        .officeContactPerson("Nərmin xanım")
                        .officeContactPhone("+994552012249")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("NERA GROUP")
                        .voen("2007855461")
                        .supplierPerson("Cəfər bəy")
                        .supplierPhone("+994558751145")
                        .officeContactPerson("Nicat bəy")
                        .officeContactPhone("+994553229777")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("AGRO TREND")
                        .voen("1702992711")
                        .address("Abşoren taxıl")
                        .supplierPerson("Mühasib")
                        .supplierPhone("+994502096488")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("BRENDSTONE")
                        .voen("1008417851")
                        .address("Sahil qəsəbəsi")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.HIGH)
                        .notes("Ödəniş sıxıntısı")
                        .build(),

                Customer.builder()
                        .companyName("LAKE CİTY")
                        .voen("1403478841")
                        .address("Nerimanov ray Asiq Molla Cume kucesi 56/2A.Omur klinikasinin yani Minera 5 mer bina")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("RIF LIFTINQ")
                        .voen("1006871261")
                        .address("Bakı şəhəri Böyükşor şossesi ,Bakı Olimpiya Stadionu VİP giriş")
                        .supplierPerson("İltifat bəy")
                        .supplierPhone("+994502632097")
                        .officeContactPerson("Arzu xanım")
                        .officeContactPhone("+994507988584")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("U.S.ENGINEERING")
                        .voen("2006777661")
                        .address("Əhməd Rəcəbli 186 Black Pearly Plaza 5 ci mər baş ofis net inşaat binası")
                        .supplierPerson("Çingiz bəy")
                        .supplierPhone("+994502710569")
                        .officeContactPerson("Bella xanım")
                        .officeContactPhone("+994504313774")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.HIGH)
                        .notes("Ödəniş sıxıntısı")
                        .build(),

                Customer.builder()
                        .companyName("EGE YAPI")
                        .voen("1405835961")
                        .address("Marine plaza")
                        .supplierPerson("Elçin bəy")
                        .supplierPhone("+994516124867")
                        .officeContactPerson("Elçin bəy")
                        .officeContactPhone("+994516124867")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("ELECTRO İNDUSTRİES")
                        .voen("1401816761")
                        .address("Ziya Bünyadov ev 11 məh 2062, Socar YDM ilə üzbəüz olan Koroğlu m Dərnəgül istiqamətinə gələndə 1 ci Santral Electri")
                        .supplierPerson("Elməddin bəy")
                        .supplierPhone("+994502548222")
                        .officeContactPerson("Ramal bəy")
                        .officeContactPhone("+994502957573")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.HIGH)
                        .notes("İş periodunda ödəniş və sənədləşmə")
                        .build(),

                Customer.builder()
                        .companyName("AZERTEXNOLAYN")
                        .voen("1601517431")
                        .address("STP")
                        .supplierPerson("Ramal bəy")
                        .supplierPhone("+994502865122")
                        .officeContactPerson("Fəxriyyə xanım(sənədləşmə)")
                        .officeContactPhone("+994705243832")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("TVM İNŞAAT")
                        .voen("1101408601")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.MEDIUM)
                        .build(),

                Customer.builder()
                        .companyName("KOLİN")
                        .voen("1008535601")
                        .address("Nəsimi rayonu,A.Əliyev küçəsi ev 6. Köhnə Küveyt Səfirilinin binası")
                        .supplierPerson("Mehmet bəy")
                        .supplierPhone("+994552255386")
                        .officeContactPerson("Uğur bəy")
                        .officeContactPhone("+994552149140")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("CBS CONSTRUCTION")
                        .voen("1007698351")
                        .supplierPerson("Vüqar bəy")
                        .supplierPhone("+995554446695")
                        .officeContactPerson("Vüqar bəy")
                        .officeContactPhone("+995554446695")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.ACTIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("HN CONSTRUCTION")
                        .voen("1304302851")
                        .address("İ.Talıblı küç. 27A Hədəf kurs 8-ci mərtəbə")
                        .supplierPerson("Ehtiram bəy")
                        .supplierPhone("+994503569352")
                        .officeContactPerson("Röya xanım")
                        .officeContactPhone("+994554449020")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("İdeal TM")
                        .voen("1401473051")
                        .address("İ.Talıblı küç. 27A Hədəf kurs 8-ci mərtəbə")
                        .supplierPerson("Ehtiram bəy")
                        .supplierPhone("+994503569352")
                        .officeContactPerson("Röya xanım")
                        .officeContactPhone("+994554449020")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("İMA-ENERGY")
                        .voen("1601005511")
                        .supplierPerson("Təchizat")
                        .supplierPhone("+994554143585")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.HIGH)
                        .build(),

                Customer.builder()
                        .companyName("BAKU TRADE SUPPLY")
                        .voen("1805311051")
                        .supplierPerson("Hacı bəy")
                        .supplierPhone("+994502558189")
                        .officeContactPerson("Hacı bəy")
                        .officeContactPhone("+994502558189")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.ACTIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("POWERCHINA")
                        .voen("1406539791")
                        .address("Sumqayıt şəh.")
                        .officeContactPerson("Ruslan bəy")
                        .officeContactPhone("+994102530019")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.MEDIUM)
                        .build(),

                Customer.builder()
                        .companyName("OASİS")
                        .voen("1003011271")
                        .address("Hövsan Zeytin dairəsi")
                        .supplierPerson("Koray bəy")
                        .supplierPhone("+994505775737")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("HYDROSERV")
                        .voen("1700095541")
                        .address("Salyan şossesi 15")
                        .supplierPerson("Rafail bəy")
                        .supplierPhone("+994502819611")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("CE PARTS")
                        .voen("1405421941")
                        .address("Bakı Sumqayıt şosesi 5km x")
                        .supplierPerson("Təchizat")
                        .supplierPhone("+994552540324")
                        .officeContactPerson("Günel xanım (Sənədləşmə)")
                        .officeContactPhone("+994512707715")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("SUPPLYING ULTIMATE RENTALS")
                        .voen("3103993331")
                        .address("Əhməd Rəcəbli")
                        .supplierPerson("Azər bəy")
                        .supplierPhone("+994557011636")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("TRANSLİFT")
                        .voen("2006037141")
                        .address("Ağ şəhər ,Sahil 14 . yaşıl ada 1")
                        .supplierPerson("Rauf Aydın(Direktor)")
                        .supplierPhone("+994502140994")
                        .officeContactPerson("Hicranə xanım")
                        .officeContactPhone("+994502507013")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("AZERİ MİNİNG GROUP")
                        .voen("1005352921")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("GP SOY PROCESSİNG")
                        .voen("1503242161")
                        .address("Absheron taxıl MMC, Xırdalan")
                        .supplierPerson("Tahir Əliyev")
                        .supplierPhone("+994504891705")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("REBA GROUP")
                        .voen("1806410491")
                        .address("Bakı ş Sabunçu rayonu Bakıxanov qəs Mehmandarov küç")
                        .supplierPerson("Aleksandra xanım")
                        .supplierPhone("+994557832173")
                        .officeContactPerson("Əməkdaş")
                        .officeContactPhone("+994102252638")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.PASSIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build(),

                Customer.builder()
                        .companyName("QALA GROUP MMC")
                        .voen("1601355741")
                        .address("Sabah rezident")
                        .officeContactPerson("İntizar xanım")
                        .officeContactPhone("+994506808222")
                        .paymentTypes(Set.of("TRANSFER"))
                        .status(CustomerStatus.ACTIVE)
                        .riskLevel(RiskLevel.LOW)
                        .build()
        );

        customerRepository.saveAll(customers);
        log.info("{} müştəri əlavə edildi.", customers.size());
    }
}
