package com.ces.erp.enums;

public enum RequestStatus {
    DRAFT,
    PENDING,
    PM_REVIEW,
    PM_SHORTLIST_READY,
    COORDINATOR_NEGOTIATING,
    COORDINATOR_PROPOSED,
    PM_PRICE_NEGOTIATION,
    PM_APPROVED,
    ACCOUNTING_DOCS_CHECK,
    EXECUTION_READY,
    OPERATOR_ASSIGNED,
    EQUIPMENT_DISPATCHED,
    DELIVERED,
    REJECTED
}
