name: Deploy Backend

on:
  push:
    branches: ["*"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER2_SSH_HOST }}
          username: ${{ secrets.SERVER2_SSH_USER }}
          key: ${{ secrets.SERVER2_BACKEND_KEY }}
          script: |
            cd /opt/cesapp
            git -C backend pull
            docker compose up -d --build backend
            echo "Backend deploy tamamlandı!"
